name: Added palceholder ssh
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }} "cd /home/pi/Git/RoryBot && git fetch && git checkout feature/github_ssh_actions && git reset --hard && git pull && npm install && chown $(whoami) && npm run restart"

          #     - name: Restart Node Server
          # uses: appleboy/ssh-action@v0.1.6
          # with:
          #   host: ${{ secrets.SSH_HOST_IP }}
          #   username: ${{ secrets.SSH_USER }}
          #   key: ${{ secrets.SSH_PRIVATE_KEY }}
          #   port: ${{ secrets.SSH_PORT }}
          #   script: |
          #     cd /home/pi/Git/RoryBot
          #     npm install
          #     chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
          #     npm run restart