name: CI Deployment Prod
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/pi/Git/RoryBot
            git fetch
            git checkout main --force
            git reset --hard
            git pull
            source /home/pi/.config/nvm/nvm.sh
            npm i
            npm run deploy
            npm restart